apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ec10kznag-nodejs
  janus-idp.io/tekton: ec10kznag-nodejs
  backstage.io/kubernetes-id: ec10kznag-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ec10kznag-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
