apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ec10kznag-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec10kznag-nodejs 
  name: ec10kznag-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ec10kznag-nodejs 
